ACTION_FORWARD = KEY_W
ACTION_FORWARD_UP = KEY_UP

ACTION_DOWN_S = KEY_S
ACTION_DOWN = KEY_DOWN

ACTION_MOVE_LEFT_A = KEY_A 
ACTION_MOVE_LEFT = KEY_NOTHING

ACTION_MOVE_RIGHT_D = KEY_D
ACTION_MOVE_RIGHT = KEY_NOTHING

ACTION_TURN_RIGHT_E = KEY_E
ACTION_TURN_RIGHT = KEY_RIGHT

ACTION_TURN_LEFT_Q = KEY_Q
ACTION_TURN_LEFT = KEY_LEFT


ACTION_USE = KEY_SPACE
ACTION_ENTER = KEY_ENTER

ACTION_INVENTORY = KEY_I
ACTION_LOG = KEY_L
ACTION_BACK = KEY_ESC
ACTION_QUIT = KEY_ESC
ACTION_OPEN = KEY_O
ACTION_THROW = KEY_T
ACTION_VIEW = KEY_V
ACTION_CLIMB_STAIRS = KEY_BRACKET_NEXT

ACTION_DROP = KEY_P
ACTION_PICK_UP = KEY_P

ACTION_FAVORITE = KEY_F

ACTION_HELP = KEY_QUESTION

ACTION_VIEW_MAP = KEY_M

ACTION_VIEW = KEY_V

ACTION_PAGE_UP = KEY_PGN_UP
ACTION_PAGE_DOWN = KEY_PGN_DOWN

ACTION_VIEW_STATS = KEY_2